### A. where behavior, ripple, parsed replay data lives

In [1]:
%reload_ext autoreload
%autoreload 2

In [3]:
import os
import pickle
import spyglass as nd
import pandas as pd
import statsmodels.api as sm
# ignore datajoint+jupyter async warnings
import warnings
warnings.simplefilter('ignore', category=DeprecationWarning)
warnings.simplefilter('ignore', category=ResourceWarning)

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import logging
import multiprocessing

FORMAT = '%(asctime)s %(message)s'

logging.basicConfig(level='INFO', format=FORMAT, datefmt='%d-%b-%y %H:%M:%S')

from spyglass.common import (Session, IntervalList,IntervalPositionInfo,
                             LabMember, LabTeam, Raw, Session, Nwbfile,
                            Electrode,LFPBand,interval_list_intersect)
from spyglass.common.common_interval import _intersection

#from spyglass.common.nwb_helper_fn import get_nwb_copy_filename
from spyglass.common.common_position import IntervalPositionInfo, IntervalPositionInfoSelection


# Here are the analysis tables specific to Shijie Gu
from spyglass.shijiegu.Analysis_SGU import (TrialChoice,
                                            TrialChoiceReplay,
                                            RippleTimes,
                                            Decode,
                                            TrialChoiceReplayTransition,
                                            get_linearization_map,
                                            find_ripple_times,classify_ripples,classify_ripple_content)
from spyglass.shijiegu.PastFuture_Replay import (replay_in_categories,find_distinct_subset,proportion,
                                                 unravel_replay,count_replay_by_category,category_day)

In [4]:
pd.set_option('display.max_rows', None)

### 1. Animal's behavior + classified replay contents + replayed arm transitions
These data are in the Table ```TrialChoiceReplayTransition```in the database. In the subfield ```choice_reward_replay_transition```

Parsed replayed transitions at the home well for each trial is in the column ```replayed_transitions```

IMPORTANT: Note that only legal trials are included. Feel free to use this version of behavior dataset.

In [5]:
'''
Just take a look at the table. 
With the two entries "nwb_file_name" and "epoch",
    you can retrieve other information in the table.
    See more in the cells below.
'''
TrialChoiceReplayTransition()

*nwb_file_name *epoch    epoch_name     transition choice_rew
+------------+ +-------+ +------------+ +--------+ +--------+
molly20220415_ 2         02_SeqSession1 =BLOB=     =BLOB=
molly20220415_ 4         04_Seq2Session =BLOB=     =BLOB=
molly20220415_ 6         06_Seq2Session =BLOB=     =BLOB=
molly20220415_ 8         08_Seq2Session =BLOB=     =BLOB=
molly20220416_ 2         02_Seq2Session =BLOB=     =BLOB=
molly20220416_ 4         04_Seq2Session =BLOB=     =BLOB=
molly20220416_ 6         06_Seq2Session =BLOB=     =BLOB=
molly20220416_ 8         08_Seq2Session =BLOB=     =BLOB=
molly20220416_ 10        10_Seq2Session =BLOB=     =BLOB=
molly20220417_ 2         02_Seq2Session =BLOB=     =BLOB=
molly20220417_ 4         04_Seq2Session =BLOB=     =BLOB=
molly20220417_ 6         06_Seq2Session =BLOB=     =BLOB=
   ...
 (Total: 30)

In [6]:
'''choose a day'''
nwb_copy_file_name='molly20220420_.nwb'
all_epochs=list((TrialChoiceReplayTransition() & 
                 {'nwb_file_name':nwb_copy_file_name}).fetch('epoch'))
print('epochs all this day:',all_epochs)

epochs all this day: [2, 4, 6, 8, 10, 12]

In [7]:
'''choose an epoch'''
epoch_num = 4

In [8]:
'''get the behavior + ripple/replay + parsed replay data on this day and this epoch'''
T=pd.DataFrame((TrialChoiceReplayTransition() & {'nwb_file_name':nwb_copy_file_name,
                                 'epoch':epoch_num}).fetch1('choice_reward_replay_transition'))
T

,timestamp_H,Home,timestamp_O,OuterWellIndex,replayed_transitions,rewardNum,ripple_H,ripple_O,replay_H,ripple_peak_H,replay_O,ripple_peak_O
1,1.650477e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650477506.9091513, 1650477506.9531515]], [...","[[[1650477522.7511444, 1650477522.7971444]], [...","[[nan], [nan, 0.0, nan], [0]]",[],"[[3], [3], [3], [3], [3], [3], [nan]]",[]
2,1.650478e+09,1.0,1.650478e+09,4.0,[],2.0,"[[[1650477535.4171388, 1650477535.5491385]], [...","[[[1650477543.0431354, 1650477543.1231353]], [...","[[0], [0], [0], [0], [0]]",[],"[[4], [4], [4], [5.0, nan], [4], [4], [4.0, na...",[]
5,1.650478e+09,1.0,1.650478e+09,3.0,[],1.0,"[[[1650477586.973116, 1650477587.0931158]], [[...","[[[1650477593.7071128, 1650477593.7911127]]]","[[0], [0]]",[],[[3]],[]
6,1.650478e+09,1.0,1.650478e+09,4.0,[],1.0,"[[[1650477598.3211107, 1650477598.4211106]], [...",[],"[[0], [0], [0]]",[],[],[]
7,1.650478e+09,1.0,1.650478e+09,2.0,[],1.0,"[[[1650477610.7611053, 1650477610.8471053]], [...","[[[1650477620.5791008, 1650477620.9031007]], [...","[[0], [0], [0]]",[],"[[2], [2], [2], [2], [2], [2], [2], [2]]",[]
8,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650477636.4330938, 1650477636.6090937]], [...","[[[1650477644.5390902, 1650477644.6130903]], [...","[[0], [0], [0], [0], [0], [0], [0], [0]]",[],"[[1], [1], [5, 1], [1], [1.0, nan], [1], [1], ...",[]
9,1.650478e+09,1.0,1.650478e+09,4.0,[],1.0,"[[[1650477660.0790832, 1650477660.1370833]], [...","[[[1650477668.1990798, 1650477668.2790797]]]","[[0], [0], [0]]",[],[[4]],[]
10,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650477674.495077, 1650477674.533077]], [[1...","[[[1650477682.0570736, 1650477682.1010735]], [...","[[0], [0], [0], [0], [0]]",[],"[[3], [3], [3], [3], [3], [3], [3], [3], [3], ...",[]
11,1.650478e+09,1.0,1.650478e+09,4.0,[],2.0,"[[[1650477700.7430654, 1650477700.8490653]], [...","[[[1650477715.8290586, 1650477715.8790586], [1...","[[0], [0], [0], [nan, 5.0], [5], [0], [0], [0]]",[],"[[4.0, nan, 4.0, nan], [3], [4]]",[]
14,1.650478e+09,1.0,1.650478e+09,3.0,[],1.0,"[[[1650477760.1910388, 1650477760.2830389]], [...",[],"[[0], [0], [0], [0], [0], [0], [4], [0], [0], ...",[],[],[]
15,1.650478e+09,1.0,1.650478e+09,4.0,[],1.0,"[[[1650477779.0210304, 1650477779.0950305]], [...","[[[1650477791.581025, 1650477791.8170247]]]","[[0], [0], [0], [0], [0], [2], [nan, 2.0, nan,...",[],[[4]],[]
16,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650477795.385023, 1650477795.4490232]], [[...","[[[1650477810.4930165, 1650477810.5690165]], [...","[[0], [0], [0], [0], [0], [2], [0], [0]]",[],"[[1], [nan], [1], [1], [1]]",[]
17,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650477832.7330067, 1650477832.7710066]], [...","[[[1650477843.0030022, 1650477843.103002]], [[...","[[0], [0], [0], [0], [0], [0], [0], [nan, 2.0,...",[],"[[3], [3], [3], [3], [3], [3], [3], [3]]",[]
18,1.650478e+09,1.0,1.650478e+09,4.0,[],2.0,"[[[1650477855.1589966, 1650477855.2209966]], [...","[[[1650477865.8829918, 1650477865.936992]], [[...","[[0], [0], [0], [0], [0], [0], [0], [2], [0], ...",[],"[[4], [nan], [4, 4], [4], [4], [4]]",[]
19,1.650478e+09,1.0,1.650478e+09,2.0,[],2.0,"[[[1650477878.5889862, 1650477878.7529862]], [...","[[[1650477889.1309814, 1650477889.1929815]], [...","[[0], [0], [0], [0], [2], [0], [0], [0]]",[],"[[2], [2], [2.0, nan, 2.0], [2], [2], [2], [2]...",[]
20,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650477901.4409761, 1650477901.636976]], [[...","[[[1650477912.930971, 1650477912.998971]], [[1...","[[0], [0], [0], [0], [0], [1], [3], [nan], [0]...",[],"[[1], [1], [1], [1], [1], [1], [1]]",[]
21,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650477940.6929586, 1650477940.7329586]], [...","[[[1650477958.7149506, 1650477958.8329506]]]","[[0], [0], [0], [0], [0], [nan], [0], [0], [0]]",[],[[3]],[]
22,1.650478e+09,1.0,1.650478e+09,4.0,"[(2, 4)]",2.0,"[[[1650477965.2989478, 1650477965.3889477]], [...","[[[1650477976.3609428, 1650477976.5229428]], [...","[[0], [0], [0], [2], [2], [4], [0], [nan], [0]...",[],"[[4], [4], [4]]",[]
23,1.650478e+09,1.0,1.650478e+09,2.0,[],2.0,"[[[1650477988.4209375, 1650477988.5149374]], [...","[[[1650478001.7389314, 1650478001.7969315]], [...","[[0], [0], [0], [0], [0], [3], [0], [2], [2.0,...",[],"[[2], [2], [2], [2.0, nan], [2], [2], [2]]",[]
24,1.650478e+09,1.0,1.650478e+09,1.0,"[(3, 1)]",2.0,"[[[1650478014.046926, 1650478014.244926]], [[1...","[[[1650478032.4129179, 1650478032.4529178]], [...","[[0], [0], [0], [0], [0], [0, 0], [0], [3], [3...",[],"[[1], [1], [1, 1], [1], [1], [1], [1], [1]]",[]
25,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650478039.9609146, 1650478040.0089145]], [...","[[[1650478051.7549093, 1650478051.7989092]], [...","[[0], [0], [0], [0], [0], [0], [0], [4], [0], ...",[],"[[3], [3], [3], [3], [3], [3], [3]]",[]
26,1.650478e+09,1.0,1.650478e+09,4.0,"[(2, 1)]",2.0,"[[[1650478066.5909028, 1650478066.6389027]], [...","[[[1650478082.0228958, 1650478082.0788958]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [2], ...",[],"[[4], [5.0, nan, 4.0]]",[]
27,1.650478e+09,1.0,1.650478e+09,2.0,"[(2, 1)]",2.0,"[[[1650478089.7048924, 1650478089.8568923]], [...","[[[1650478101.3668873, 1650478101.4268873]], [...","[[0], [0], [0], [0], [0], [0], [0], [0.0, nan,...",[],"[[2], [2], [2], [2], [2], [2], [2]]",[]
28,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650478114.1108816, 1650478114.1588817]], [...","[[[1650478127.4308758, 1650478127.5028756]], [...","[[0], [0], [0], [0], [0], [0.0, nan], [0], [0]...",[],"[[1], [1], [1], [1], [1], [1], [1], [1], [1], ...",[]
29,1.650478e+09,1.0,1.650478e+09,4.0,[],1.0,"[[[1650478142.552869, 1650478142.622869]], [[1...",[],"[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],[],[]
30,1.650478e+09,1.0,1.650478e+09,1.0,[],1.0,"[[[1650478161.5168605, 1650478161.5888605]], [...","[[[1650478176.010854, 1650478176.088854]]]","[[0], [0], [0], [3], [0], [0], [2.0, nan], [0]...",[],[[1]],[]
31,1.650478e+09,1.0,1.650478e+09,2.0,[],1.0,"[[[1650478181.134852, 1650478181.2088518]], [[...","[[[1650478194.1688461, 1650478194.286846]]]","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],[[2]],[]
32,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650478198.806844, 1650478198.8748438]], [[...","[[[1650478211.5008383, 1650478211.5668383]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [0]]",[],"[[3], [3], [3], [3], [3]]",[]
33,1.650478e+09,1.0,1.650478e+09,4.0,[],2.0,"[[[1650478223.7308328, 1650478223.7928329]], [...","[[[1650478234.954828, 1650478235.1168277]], [[...","[[0], [0], [4.0, nan, 4.0, nan], [0], [0], [0]]",[],"[[4], [4], [4], [4]]",[]
34,1.650478e+09,1.0,1.650478e+09,2.0,[],2.0,"[[[1650478248.8368218, 1650478248.8768218]], [...","[[[1650478266.330814, 1650478266.5848138]], [[...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],"[[2], [nan], [2], [2], [2]]",[]
35,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650478275.6068099, 1650478275.68481]], [[1...","[[[1650478290.9628031, 1650478291.0088031]], [...","[[0], [0], [nan, 0.0], [nan], [1, 5], [0], [0]...",[],"[[1], [1], [3], [1], [1], [1], [1]]",[]
36,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650478299.8927991, 1650478299.980799]], [[...","[[[1650478314.3527927, 1650478314.4187927]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [3], ...",[],"[[3], [3], [3], [3], [3]]",[]
37,1.650478e+09,1.0,1.650478e+09,4.0,[],2.0,"[[[1650478326.0487874, 1650478326.0967875]], [...","[[[1650478343.2347798, 1650478343.2947798]], [...","[[0], [0], [0], [0], [2], [nan, 5.0, nan], [0]...",[],"[[4], [nan, 5.0, 4.0]]",[]
38,1.650478e+09,1.0,1.650478e+09,2.0,[],2.0,"[[[1650478351.562776, 1650478351.638776]], [[1...","[[[1650478369.4547682, 1650478369.4847682]], [...","[[0], [0], [0], [0], [0], [4], [4], [0], [0], ...",[],"[[nan], [nan], [2], [2], [2]]",[]
39,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650478377.7187645, 1650478377.8367643]], [...","[[[1650478395.9467564, 1650478396.0027564]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [4], ...",[],"[[1], [1], [1], [1]]",[]
40,1.650478e+09,1.0,1.650478e+09,3.0,[],2.0,"[[[1650478404.5287526, 1650478404.5867527]], [...","[[[1650478417.0347471, 1650478417.084747]], [[...","[[0], [0], [0], [nan, 0.0], [nan], [0], [0], [...",[],"[[3], [2], [4.0, nan], [3]]",[]
41,1.650478e+09,1.0,1.650478e+09,4.0,"[(2, 4)]",2.0,"[[[1650478430.256741, 1650478430.364741]], [[1...","[[[1650478448.2427332, 1650478448.410733]], [[...","[[0], [0], [0], [0, 2], [5], [4], [0], [0], [0...",[],"[[nan], [4], [4]]",[]
42,1.650478e+09,1.0,1.650478e+09,2.0,[],2.0,"[[[1650478455.51873, 1650478455.61473]], [[165...","[[[1650478474.6267214, 1650478474.7067213]], [...","[[0], [0], [0], [0], [0], [2], [5], [0], [0.0,...",[],"[[2], [2], [2], [2], [2], [2], [2], [2], [2], ...",[]
43,1.650478e+09,1.0,1.650478e+09,1.0,[],2.0,"[[[1650478487.070716, 1650478487.1247158]], [[...","[[[1650478504.4827082, 1650478504.5327082]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],"[[1], [nan, 4.0], [nan], [nan], [1], [1], [1],...",[]
44,1.650479e+09,1.0,1.650479e+09,3.0,[],2.0,"[[[1650478513.658704, 1650478513.7727041]], [[...","[[[1650478532.2746959, 1650478532.3026958]], [...","[[0], [0], [0], [0], [0], [0], [0.0, nan, 1.0]...",[],"[[3], [3], [3]]",[]
45,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650478538.818693, 1650478538.890693]], [[1...","[[[1650478551.6286871, 1650478551.7126873]], [...","[[0], [0], [0], [0, 5], [0], [2], [0], [0], [0...",[],"[[4], [4], [4], [nan]]",[]
46,1.650479e+09,1.0,1.650479e+09,2.0,"[(1, 2)]",2.0,"[[[1650478568.0886798, 1650478568.14268]], [[1...","[[[1650478584.0906727, 1650478584.1546729]], [...","[[0], [0], [0], [0], [0], [0], [nan, 0.0], [0....",[],"[[2], [1], [2], [nan], [2], [2]]",[]
47,1.650479e+09,1.0,1.650479e+09,1.0,[],2.0,"[[[1650478595.0526679, 1650478595.126668]], [[...","[[[1650478615.4566588, 1650478615.484659]], [[...","[[0], [0], [0], [0], [0], [0], [0], [1], [0], ...",[],"[[1], [1]]",[]
48,1.650479e+09,1.0,1.650479e+09,3.0,[],2.0,"[[[1650478624.4626548, 1650478624.5686548]], [...","[[[1650478637.598649, 1650478637.640649]], [[1...","[[0], [0], [0], [0], [0], [0], [2, 5], [0], [0...",[],"[[3], [3], [3], [3]]",[]
49,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650478651.508643, 1650478651.6286428]], [[...","[[[1650478662.6966379, 1650478662.8106377]], [...","[[0], [0], [0], [0], [nan], [0], [2], [0], [0]...",[],"[[4], [4], [2], [4]]",[]
50,1.650479e+09,1.0,1.650479e+09,2.0,[],2.0,"[[[1650478676.308632, 1650478676.3626318]], [[...","[[[1650478689.9866257, 1650478690.0246258]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],"[[2], [2], [2], [2], [2], [2]]",[]
51,1.650479e+09,1.0,1.650479e+09,1.0,[],2.0,"[[[1650478708.4406176, 1650478708.4906175]], [...","[[[1650478723.466611, 1650478723.5066109]], [[...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],"[[1], [1], [1], [nan], [1], [1], [1], [1], [1....",[]
52,1.650479e+09,1.0,1.650479e+09,3.0,[],2.0,"[[[1650478736.3486052, 1650478736.448605]], [[...","[[[1650478747.6846, 1650478747.7406]], [[16504...","[[0], [0], [0], [0], [0], [0], [0.0, nan], [0]...",[],"[[3], [3], [0]]",[]
53,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650478762.4065936, 1650478762.4525936]], [...","[[[1650478779.9265857, 1650478779.9925857]], [...","[[0], [2], [0], [nan], [nan, 0.0], [0], [0], [...",[],"[[4], [4], [4]]",[]
54,1.650479e+09,1.0,1.650479e+09,2.0,"[(2, 1)]",2.0,"[[[1650478789.0345817, 1650478789.1125817]], [...","[[[1650478804.4905748, 1650478804.5305748]], [...","[[0], [0], [0], [0], [0], [0], [0], [2, 1], [0...",[],"[[2], [2], [2], [2], [2], [2], [2], [2], [2], ...",[]
55,1.650479e+09,1.0,1.650479e+09,1.0,[],2.0,"[[[1650478819.810568, 1650478819.874568]], [[1...","[[[1650478834.5085616, 1650478834.5685616]], [...","[[0], [0], [3], [0], [0], [1], [0], [0], [0], ...",[],"[[1], [1], [1], [1], [1], [1], [1], [1], [1], ...",[]
56,1.650479e+09,1.0,1.650479e+09,3.0,[],2.0,"[[[1650478850.8685544, 1650478850.9505541]], [...","[[[1650478868.7885463, 1650478868.8445463]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],"[[3], [3]]",[]
57,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650478877.1205425, 1650478877.2085426]], [...","[[[1650478895.6265345, 1650478895.6525345], [1...","[[0], [0], [0], [0], [4], [0], [0], [0], [2.0,...",[],"[[nan, 4.0], [0.0, nan, 3.0, 5.0, nan]]",[]
58,1.650479e+09,1.0,1.650479e+09,2.0,[],2.0,"[[[1650478903.9505308, 1650478904.0025306]], [...","[[[1650478916.4285252, 1650478916.476525]], [[...","[[0], [0], [0, 2], [0], [0], [0], [0], [0], [0...",[],"[[2], [2], [2], [2], [2], [2], [2], [2], [2], ...",[]
59,1.650479e+09,1.0,1.650479e+09,3.0,[],1.0,"[[[1650478937.9805155, 1650478938.0745156]], [...",[],"[[0], [0], [0], [0.0, nan], [0], [0], [0], [0....",[],[],[]
60,1.650479e+09,1.0,1.650479e+09,4.0,"[(2, 1)]",1.0,"[[[1650478959.3725061, 1650478959.412506]], [[...","[[[1650478972.2465003, 1650478972.3265004]], [...","[[0], [0], [0], [4.0, nan], [0.0, nan, 0.0], [...",[],"[[4], [nan, 4.0]]",[]
61,1.650479e+09,1.0,1.650479e+09,1.0,[],2.0,"[[[1650478983.9844952, 1650478984.0304952]], [...","[[[1650479004.096486, 1650479004.1404862], [16...","[[0], [0], [0], [1, 5], [0], [0], [0], [0], [0...",[],"[[1.0, nan], [1], [nan, 2.0, nan], [2], [1], [...",[]
62,1.650479e+09,1.0,1.650479e+09,2.0,[],1.0,"[[[1650479013.8504817, 1650479013.950482]], [[...","[[[1650479038.488471, 1650479038.5604708]], [[...","[[0], [0], [0], [0], [0], [2], [0], [0], [0], ...",[],"[[2], [2.0, nan, 3.0], [2], [2], [2], [2], [2]...",[]
63,1.650479e+09,1.0,1.650479e+09,3.0,[],2.0,"[[[1650479050.5484655, 1650479050.5884655]], [...","[[[1650479068.1744578, 1650479068.2604578]], [...","[[0], [0], [0], [0], [0], [nan, 0.0], [0], [0]...",[],"[[3], [3], [nan, nan], [3], [3], [3], [3], [3]...",[]
64,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650479082.5084515, 1650479082.5944514]], [...","[[[1650479101.8124428, 1650479101.8484428], [1...","[[0], [0], [0], [0], [0, 4], [0], [0], [nan], ...",[],"[[4.0, nan, 2.0], [], [4], [4], [4]]",[]
65,1.650479e+09,1.0,1.650479e+09,2.0,"[(1, 2), (2, 1), (1, 2)]",2.0,"[[[1650479112.1124382, 1650479112.1704383]], [...","[[[1650479127.6244314, 1650479127.6664312]], [...","[[0], [0], [0], [0], [0], [0], [1], [2.0, nan,...",[],"[[2], [2], [2], [2], [2], [2], [2], [2], [2]]",[]
66,1.650479e+09,1.0,1.650479e+09,1.0,[],2.0,"[[[1650479141.646425, 1650479141.786425]], [[1...","[[[1650479161.0684164, 1650479161.1124165]], [...","[[0], [0], [0], [0], [0], [0], [1], [0], [0], ...",[],"[[1], [1], [4]]",[]
67,1.650479e+09,1.0,1.650479e+09,3.0,"[(3, 2)]",2.0,"[[[1650479170.814412, 1650479170.874412]], [[1...","[[[1650479183.4464066, 1650479183.5524065]], [...","[[0], [0], [0], [0], [0], [0], [nan, 2.0], [0]...",[],"[[3], [3], [2], [3], [3], [3]]",[]
68,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650479198.1104, 1650479198.1764]], [[16504...","[[[1650479211.732394, 1650479211.766394]], [[1...","[[0], [0], [0], [0], [0], [0], [0], [0]]",[],"[[nan], [4], [nan, 4.0]]",[]
69,1.650479e+09,1.0,1.650479e+09,2.0,[],2.0,"[[[1650479221.0743897, 1650479221.1503897]], [...","[[[1650479236.486383, 1650479236.556383]], [[1...","[[0], [0], [0], [0], [0], [0], [0], [4.0, nan,...",[],"[[2], [2], [2], [2], [2.0, nan], [2]]",[]
70,1.650479e+09,1.0,1.650479e+09,1.0,"[(2, 4)]",2.0,"[[[1650479252.146376, 1650479252.266376]], [[1...","[[[1650479270.9943676, 1650479271.0843675]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],"[[1], [1], [5.0, nan], [1], [1], [1]]",[]
71,1.650479e+09,1.0,1.650479e+09,3.0,[],2.0,"[[[1650479287.86436, 1650479287.9523602]], [[1...","[[[1650479304.4643528, 1650479304.5283527]], [...","[[0], [0], [0], [0], [0], [0], [0], [nan, 0.0]...",[],"[[3], [3], [3], [nan], [2], [3], [3]]",[]
72,1.650479e+09,1.0,1.650479e+09,4.0,[],2.0,"[[[1650479318.6863465, 1650479318.7663465]], [...","[[[1650479330.3163412, 1650479330.3663414]], [...","[[0], [0], [0], [0], [0], [0], [4], [0.0, nan]...",[],"[[4], [4]]",[]
73,1.650479e+09,1.0,1.650479e+09,2.0,[],2.0,"[[[1650479344.886335, 1650479344.9483347]], [[...","[[[1650479391.538314, 1650479391.630314]], [[1...","[[0], [0], [0], [0], [0.0, 2.0, nan, 5.0], [0]...",[],"[[2], [2], [2], [2], [2], [3], [2], [2], [2], ...",[]
74,1.650479e+09,1.0,1.650479e+09,3.0,[],1.0,"[[[1650479414.9623036, 1650479415.0063035]], [...",[],"[[0], [0], [0], [0], [0], [0], [0], [0], [0], ...",[],[],[]
75,1.650479e+09,1.0,1.650479e+09,4.0,"[(4, 2)]",1.0,"[[[1650479436.1522942, 1650479436.2042942]], [...",[],"[[0], [0], [0], [0], [0], [5.0, 4.0, nan], [0]...",[],[],[]
76,1.650479e+09,1.0,1.650479e+09,1.0,[],2.0,"[[[1650479454.762286, 1650479454.8922858]], [[...","[[[1650479470.146279, 1650479470.200279]], [[1...","[[0], [0], [0], [0], [0], [0], [0], [1], [0], ...",[],"[[1], [1], [1], [1], [1], [3], [1], [1], [1]]",[]
77,1.650479e+09,1.0,1.650480e+09,3.0,[],2.0,"[[[1650479486.366272, 1650479486.4642718]], [[...","[[[1650479510.2922614, 1650479510.3522613]], [...","[[0], [0], [0], [0], [0], [3], [0], [0], [0], ...",[],"[[3], [3], [1], [2], [3]]",[]
78,1.650480e+09,1.0,1.650480e+09,4.0,[],2.0,"[[[1650479520.7262566, 1650479520.8882565]], [...","[[[1650479531.5782518, 1650479531.646252]], [[...","[[0], [0], [0], [4], [4.0, nan], [0], [nan, 0....",[],"[[4], [nan, 4.0], [4], [4], [nan, 4.0, 4.0]]",[]
79,1.650480e+09,1.0,1.650480e+09,2.0,[],2.0,"[[[1650479546.5322452, 1650479546.592245]], [[...","[[[1650479563.6522377, 1650479563.7622375]], [...","[[0], [0], [0], [0], [nan, 3.0], [0], [nan], [0]]",[],"[[2], [3, 2], [2], [2], [2], [2], [2], [2], [2...",[]
80,1.650480e+09,1.0,1.650480e+09,1.0,[],2.0,"[[[1650479578.754231, 1650479578.9022307]], [[...","[[[1650479592.6762247, 1650479592.7262247]], [...","[[0], [0], [0], [0], [0], [0], [0], [0], [4.0,...",[],"[[1], [nan], [1], [1], [1], [1], [1], [1], [1]...",[]
81,1.650480e+09,1.0,1.650480e+09,3.0,"[(3, 2)]",2.0,"[[[1650479613.8462152, 1650479613.9262152]], [...","[[[1650479641.8342028, 1650479641.884203]], [[...","[[0], [0], [0, 0], [0], [0], [0], [0], [nan, 4...",[],"[[3], [nan, 3.0, nan, 3.0], [3], [3], [3], [3]...",[]

### 2. all replayed arm transitions and all replayed singleton arm count
These data are in the Table ```TrialChoiceReplayTransition```in the database. Subfield ```transitions```

Entry [i,j] means the number of a replay event of arm i followed by arm j within 200 ms, when i not equal to j.


The diagonal entries [i,i] are the number of singleton replays of arm i. The diagonal entries are over-counted due to the lick artifact in the neural data splitting a smooth replay into 2. Take the diagonal entries as a grain of salt for Molly's data.

In [9]:
transitions_all=(TrialChoiceReplayTransition() &
                 {'nwb_file_name':nwb_copy_file_name,
                  'epoch':epoch_num}).fetch1('transitions')
transitions_all

array([[17.,  3.,  0.,  0.],
       [ 5., 21.,  0.,  3.],
       [ 1.,  2., 13.,  0.],
       [ 0.,  1.,  0., 18.]])

### 3. Animal's behavior + annotated future, past, past reward arms
These data is in the table called ```TrialChoice()``` in the database.


IMPORTANT: Note that ALL trials are included, as opposed to legal trials only.

In [10]:
TrialChoice()

*nwb_file_name *epoch    epoch_name     choice_rew
+------------+ +-------+ +------------+ +--------+
molly20220415_ 2         02_SeqSession1 =BLOB=
molly20220415_ 4         04_Seq2Session =BLOB=
molly20220415_ 6         06_Seq2Session =BLOB=
molly20220415_ 8         08_Seq2Session =BLOB=
molly20220416_ 2         02_Seq2Session =BLOB=
molly20220416_ 4         04_Seq2Session =BLOB=
molly20220416_ 6         06_Seq2Session =BLOB=
molly20220416_ 8         08_Seq2Session =BLOB=
molly20220416_ 10        10_Seq2Session =BLOB=
molly20220417_ 2         02_Seq2Session =BLOB=
molly20220417_ 4         04_Seq2Session =BLOB=
molly20220417_ 6         06_Seq2Session =BLOB=
   ...
 (Total: 30)

#### Notes:
At home well: 
- Future arm is in the column ```future_H```, which corresponds to the arm the rat will choose on this trial.
    
At arm well: 

- Future arm is in the column ```future_O```, which corresponds to the arm the rat will choose on the next trial.
    
For both home and arm well:
    
   - Past arm is in the column ```past```, which corresponds to the arm the rat was at on the last trial.
   
   - Past rewarded arm is in the column ```past_reward```, which corresponds to the arm the rat was at on the last trial, and in addition, he got a reward there.

In [11]:
T=(TrialChoice() &{'nwb_file_name':nwb_copy_file_name,
                  'epoch':epoch_num}).fetch1('choice_reward')

In [12]:
T=pd.DataFrame(T)
T

,timestamp_H,Home,timestamp_O,OuterWellIndex,rewardNum,current,future_H,future_O,past,past_reward
1,1.650477e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,NaN,NaN
2,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
3,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
4,NaN,NaN,1.650478e+09,1.0,0.0,1.0,1.0,3.0,2.0,2.0
5,1.650478e+09,1.0,1.650478e+09,3.0,1.0,3.0,3.0,4.0,1.0,2.0
6,1.650478e+09,1.0,1.650478e+09,4.0,1.0,4.0,4.0,2.0,3.0,2.0
7,1.650478e+09,1.0,1.650478e+09,2.0,1.0,2.0,2.0,1.0,4.0,2.0
8,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,4.0,2.0,2.0
9,1.650478e+09,1.0,1.650478e+09,4.0,1.0,4.0,4.0,3.0,1.0,1.0
10,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,4.0,1.0
11,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
12,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
13,NaN,NaN,1.650478e+09,1.0,0.0,1.0,1.0,3.0,2.0,2.0
14,1.650478e+09,1.0,1.650478e+09,3.0,1.0,3.0,3.0,4.0,1.0,2.0
15,1.650478e+09,1.0,1.650478e+09,4.0,1.0,4.0,4.0,1.0,3.0,2.0
16,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,3.0,4.0,2.0
17,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
18,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
19,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
20,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
21,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
22,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
23,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
24,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
25,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
26,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
27,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
28,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,4.0,2.0,2.0
29,1.650478e+09,1.0,1.650478e+09,4.0,1.0,4.0,4.0,1.0,1.0,1.0
30,1.650478e+09,1.0,1.650478e+09,1.0,1.0,1.0,1.0,2.0,4.0,1.0
31,1.650478e+09,1.0,1.650478e+09,2.0,1.0,2.0,2.0,3.0,1.0,1.0
32,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,2.0,1.0
33,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
34,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
35,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
36,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
37,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
38,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
39,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
40,1.650478e+09,1.0,1.650478e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
41,1.650478e+09,1.0,1.650478e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
42,1.650478e+09,1.0,1.650478e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
43,1.650478e+09,1.0,1.650478e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
44,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
45,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
46,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
47,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
48,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
49,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
50,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
51,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
52,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
53,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
54,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
55,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
56,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
57,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
58,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,3.0,4.0,4.0
59,1.650479e+09,1.0,1.650479e+09,3.0,1.0,3.0,3.0,4.0,2.0,2.0
60,1.650479e+09,1.0,1.650479e+09,4.0,1.0,4.0,4.0,1.0,3.0,2.0
61,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,2.0,4.0,2.0
62,1.650479e+09,1.0,1.650479e+09,2.0,1.0,2.0,2.0,3.0,1.0,1.0
63,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,2.0,1.0
64,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
65,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
66,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
67,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
68,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
69,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
70,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
71,1.650479e+09,1.0,1.650479e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
72,1.650479e+09,1.0,1.650479e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
73,1.650479e+09,1.0,1.650479e+09,2.0,2.0,2.0,2.0,3.0,4.0,4.0
74,1.650479e+09,1.0,1.650479e+09,3.0,1.0,3.0,3.0,4.0,2.0,2.0
75,1.650479e+09,1.0,1.650479e+09,4.0,1.0,4.0,4.0,1.0,3.0,2.0
76,1.650479e+09,1.0,1.650479e+09,1.0,2.0,1.0,1.0,3.0,4.0,2.0
77,1.650479e+09,1.0,1.650480e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
78,1.650480e+09,1.0,1.650480e+09,4.0,2.0,4.0,4.0,2.0,3.0,3.0
79,1.650480e+09,1.0,1.650480e+09,2.0,2.0,2.0,2.0,1.0,4.0,4.0
80,1.650480e+09,1.0,1.650480e+09,1.0,2.0,1.0,1.0,3.0,2.0,2.0
81,1.650480e+09,1.0,1.650480e+09,3.0,2.0,3.0,3.0,4.0,1.0,1.0
82,1.650480e+09,1.0,1.650480e+09,4.0,3.0,4.0,4.0,NaN,3.0,3.0
83,1.650480e+09,1.0,NaN,NaN,0.0,NaN,NaN,NaN,4.0,NaN

In [13]:
# to find future choice on trial 5 for example.
T.loc[5,'future_H']

3.0